{% set name = "ibm-cloud-sdk-core" %}
{% set version = "3.22.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 096dd22c146848a87053f8f2bfbd5dfdf089eefe81ee1c448ca22c4304751dfd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=67.7.2
  run:
    - pyjwt >=2.8.0,<3.0.0
    - python >={{ python_min }}
    - python-dateutil >=2.8.2,<3.0.0
    - requests >=2.31.0,<3.0.0
    - urllib3 >=2.1.0,<3.0.0

test:
  imports:
    - ibm_cloud_sdk_core
    - ibm_cloud_sdk_core.authenticators
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IBM/python-sdk-core
  summary: Core library used by SDKs for IBM Cloud Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
    - BastianZim
