{% set name = "ibm-cloud-sdk-core" %}
{% set version = "3.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c4d492256252793b72fb1500f92fe26f2e756cee7ab815fe9d987be05e38f43

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.7
  run:
    - pyjwt <3.0.0,>=2.8.0
    - python >=3.7
    - python-dateutil <3.0.0,>=2.8.2
    - requests <2.32.3,>=2.31.0
    - urllib3 <3.0.0,>=2.1.0

test:
  imports:
    - ibm_cloud_sdk_core
    - ibm_cloud_sdk_core.authenticators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/python-sdk-core
  summary: Core library used by SDKs for IBM Cloud Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
    - BastianZim
