{% set name = "ibm-cloud-sdk-core" %}
{% set version = "3.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0aa5abc972b7d70ee4c39e3ad69c82c9717be847e5672928b416b8ea7d57a297

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=67.7.2
  run:
    - pyjwt >=2.8.0,<3.0.0
    - python >=3.8
    - python-dateutil >=2.8.2,<3.0.0
    - requests >=2.31.0,<3.0.0
    - urllib3 >=2.1.0,<3.0.0

test:
  imports:
    - ibm_cloud_sdk_core
    - ibm_cloud_sdk_core.authenticators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/python-sdk-core
  summary: Core library used by SDKs for IBM Cloud Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
    - BastianZim
