{% set name = "ibm-cloud-sdk-core" %}
{% set version = "3.24.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 841d027e4f0019a7e2f0bfa64c8234e53a9654f8bbeb02f8d4068c363eb428eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=67.7.2
  run:
    - pyjwt >=2.10.1,<3.0.0
    - python >={{ python_min }}
    - python-dateutil >=2.9.0,<3.0.0
    - requests >=2.32.4,<3.0.0
    - urllib3 >=2.4.0,<3.0.0

test:
  imports:
    - ibm_cloud_sdk_core
    - ibm_cloud_sdk_core.authenticators
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IBM/python-sdk-core
  summary: Core library used by SDKs for IBM Cloud Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
    - BastianZim
